### ISSUE TITLE
Is KernelSU working in your build?

### ISSUE THREAD

**Issue by Edremon** [cawilliamson/rooted-graphene#2]
I recently tried to add KernelSU to my graphene build.

I'm using a similar build process as your but without susfs, kernel built successfully with kernelsu message during build, I correctly copied kernel to my graphene repo, then I build graphene and signed it. But, after flashing, KernelSU say that it isn't installed, and I checked dmesg and didn't see anything from KernelSU. I double checked and it's using the kernel that I had built.

So, I was wondering, is your build correctly working with KernelSU?

**Comment by cawilliamson** [comment]
Ah I wonder if you have the same weird problem I had.

This is going to sound strange but:

1. Download the latest KernelSU manager APK
2. Install and launch it
3. Says "you're not rooted" probably
4. Reinstall that APK and launch it again
5. Should say you're rooted!

If this fixed your problem it will break again next reboot but there's a way to fix that too!

Download and install any magisk module you like - doesn't matter what it is. Reboot.

You should know stay rooted properly forever using this method.

I have zero clue why this worked for me but it did and it's never been broken since even after removing all magisk modules again.
